import type { Metadata } from "next";
import "./globals.scss";
import Providers from "./components/Providers";
import { getServerSession } from "next-auth";
import NavBar from "./components/nav-bar/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body>
        <Providers session={session}>
          <NavBar />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
